import { defineTemplate, options } from "./_helpers";

/** Education → Home Tutor (ProTutors Bogura block on home, D-18). */
export const homeTutor = defineTemplate({
  key: "home_tutor",
  name: "হোম টিউটর",
  kind: "REQUEST",
  description: "Home tutor request",
  schema: {
    schemaVersion: 1,
    kind: "REQUEST",
    common: {
      address: "required",
      preferredDate: "optional",
      preferredTimeSlot: "hidden",
      notes: "optional",
      photos: "hidden",
      altPhone: "optional",
    },
    sections: [
      {
        key: "student",
        title: { bn: "শিক্ষার্থীর তথ্য", en: "Student" },
        fields: [
          {
            key: "studentClass",
            type: "select",
            label: { bn: "শ্রেণি", en: "Class" },
            required: true,
            summary: true,
            options: options([
              ["play_5", "প্লে – ৫ম শ্রেণি", "Play–5"],
              ["6_8", "৬ষ্ঠ – ৮ম শ্রেণি", "6–8"],
              ["ssc", "এসএসসি (৯ম–১০ম)", "SSC (9–10)"],
              ["hsc", "এইচএসসি (একাদশ–দ্বাদশ)", "HSC (11–12)"],
              ["admission", "ভর্তি প্রস্তুতি", "Admission"],
              ["o_a_level", "ও / এ লেভেল", "O/A level"],
              ["university", "বিশ্ববিদ্যালয়", "University"],
              ["other", "অন্যান্য", "Other"],
            ]),
          },
          {
            key: "medium",
            type: "radio",
            label: { bn: "মাধ্যম", en: "Medium" },
            required: true,
            summary: true,
            options: options([
              ["bangla", "বাংলা মাধ্যম", "Bangla medium"],
              ["english_version", "ইংলিশ ভার্সন", "English version"],
              ["english_medium", "ইংলিশ মিডিয়াম", "English medium"],
              ["madrasa", "মাদ্রাসা", "Madrasa"],
            ]),
          },
          {
            key: "group",
            type: "radio",
            label: { bn: "বিভাগ", en: "Group" },
            showIf: { field: "studentClass", op: "in", value: ["ssc", "hsc"] },
            options: options([
              ["science", "বিজ্ঞান", "Science"],
              ["commerce", "ব্যবসায় শিক্ষা", "Commerce"],
              ["arts", "মানবিক", "Arts"],
            ]),
          },
          {
            key: "subjects",
            type: "checkboxes",
            label: { bn: "বিষয়", en: "Subjects" },
            required: true,
            summary: true,
            options: options([
              ["all", "সব বিষয়", "All subjects"],
              ["bangla", "বাংলা", "Bangla"],
              ["english", "ইংরেজি", "English"],
              ["math", "গণিত", "Math"],
              ["higher_math", "উচ্চতর গণিত", "Higher math"],
              ["physics", "পদার্থবিজ্ঞান", "Physics"],
              ["chemistry", "রসায়ন", "Chemistry"],
              ["biology", "জীববিজ্ঞান", "Biology"],
              ["ict", "আইসিটি", "ICT"],
              ["accounting", "হিসাববিজ্ঞান", "Accounting"],
              ["arabic", "আরবি", "Arabic"],
              ["quran", "কুরআন শিক্ষা", "Quran"],
            ]),
          },
          {
            key: "studentCount",
            type: "number",
            label: { bn: "শিক্ষার্থী কয়জন", en: "Students" },
            defaultValue: 1,
            validation: { min: 1, max: 10 },
            width: "half",
          },
          {
            key: "studentGender",
            type: "radio",
            label: { bn: "শিক্ষার্থী", en: "Student gender" },
            width: "half",
            options: options([
              ["male", "ছেলে", "Male"],
              ["female", "মেয়ে", "Female"],
              ["mixed", "ছেলে ও মেয়ে", "Mixed"],
            ]),
          },
        ],
      },
      {
        key: "tutor",
        title: { bn: "শিক্ষক ও সময়", en: "Tutor & schedule" },
        fields: [
          {
            key: "tutorGender",
            type: "radio",
            label: { bn: "শিক্ষক", en: "Tutor gender" },
            required: true,
            options: options([
              ["male", "পুরুষ", "Male"],
              ["female", "মহিলা", "Female"],
              ["any", "যেকোনো", "Any"],
            ]),
          },
          {
            key: "daysPerWeek",
            type: "select",
            label: { bn: "সপ্তাহে কত দিন", en: "Days per week" },
            required: true,
            width: "half",
            options: options([
              ["2", "২ দিন"],
              ["3", "৩ দিন"],
              ["4", "৪ দিন"],
              ["5", "৫ দিন"],
              ["6", "৬ দিন"],
            ]),
          },
          {
            key: "preferredTime",
            type: "time",
            label: { bn: "পছন্দের সময়", en: "Preferred time" },
            width: "half",
          },
          {
            key: "salaryBudget",
            type: "money",
            label: { bn: "মাসিক বেতন (টাকা)", en: "Monthly salary" },
            required: true,
            summary: true,
            validation: { min: 500, max: 100000 },
          },
          {
            key: "tutorPreference",
            type: "checkboxes",
            label: { bn: "শিক্ষকের বিষয়ে পছন্দ", en: "Tutor preference" },
            options: options([
              ["university_student", "বিশ্ববিদ্যালয়ের শিক্ষার্থী", "University student"],
              ["experienced_teacher", "অভিজ্ঞ শিক্ষক", "Experienced teacher"],
              ["specific_institution", "নির্দিষ্ট প্রতিষ্ঠান থেকে", "Specific institution"],
            ]),
          },
          {
            key: "institutionName",
            type: "text",
            label: { bn: "কোন প্রতিষ্ঠান", en: "Institution" },
            placeholder: { bn: "যেমন: সরকারি আজিজুল হক কলেজ" },
            validation: { maxLength: 80 },
            showIf: { field: "tutorPreference", op: "in", value: ["specific_institution"] },
          },
        ],
      },
    ],
  },
});
